name: Generate Snake

on:
  # Her gece yarısı otomatik çalıştır
  schedule:
    - cron: "0 0 * * *" 
  
  # Manuel çalıştırmaya da izin ver
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # GitHub kullanıcı adın
          github_user_name: HyperDeathh
          # Çıktı dosyalarının nereye kaydedileceği
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to the output branch
        uses: crazy-max/gh-action-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
